# fly.toml file generated for iiroki-influxdb on 2023-02-25T11:34:11+02:00

app = "iiroki-influxdb"

[mounts]
  destination = "/var/lib/influxdb2"
  source = "influxdb_data"

[[services]]
  internal_port = 8086
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
